#!/usr/bin/env bash
#
# Generates loaded_gwenesis_rom.c for the Linux build (Makefile.gwenesis).
#
# Gwenesis already applies a 16-bit byte swap (ROM_SWAP) in load_cartridge() after
# memcpy - same logic as a .bin loaded from the SD card on the target.
# For Gwenesis ROMs, we always swap each pair of bytes (i,i+1) BEFORE embedding.
#
# Usage:
#   ./update_gwenesis_rom.sh <rom.bin|gen|md> [loaded_gwenesis_rom.c]
#
# It does not generate a global ROM_DATA[] symbol: the core uses the ROM_DATA
# pointer (gwenesis_bus.c) assigned from gwenesis_embedded_rom.
#
set -euo pipefail
while [[ $# -gt 0 ]]; do
    case "$1" in
        --swap-pairs)
            # Compatibility: historically this option enabled the swap.
            # The swap is now always active; keep this flag to avoid breaking
            # existing scripts.
            echo "Note: --swap-pairs is now unnecessary (always active)." >&2
            shift
            ;;
        -h|--help)
            sed -n '1,22p' "$0"
            exit 0
            ;;
        *) break ;;
    esac
done

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <megadrive_rom> [out.c]" >&2
    exit 1
fi

INFILE=$1
OUTFILE=${2:-loaded_gwenesis_rom.c}

if [[ ! -f "$INFILE" ]]; then
    echo "File not found: $INFILE" >&2
    exit 1
fi

python3 - "$INFILE" "$OUTFILE" <<'PY'
import sys

inpath, outpath = sys.argv[1], sys.argv[2]
swap_pairs = True  # Always active for Gwenesis dumps expected by the core.

with open(inpath, "rb") as f:
    data = bytearray(f.read())

size = len(data)

if swap_pairs:
    for i in range(0, len(data) - 1, 2):
        data[i], data[i + 1] = data[i + 1], data[i]

base = inpath.split("/")[-1]

with open(outpath, "w") as out:
    out.write("/* Generated by update_gwenesis_rom.sh - do not edit */\n")
    out.write("/* Source: %s | swap_pairs=%s */\n" % (inpath, swap_pairs))
    out.write("#include <stdint.h>\n")
    out.write("const unsigned char gwenesis_embedded_rom[] = {\n")
    line = []
    for i, b in enumerate(data):
        line.append("0x%02x" % b)
        if len(line) >= 12 or i == len(data) - 1:
            out.write("  " + ", ".join(line) + ",\n")
            line = []
    out.write("};\n")
    out.write("const uint32_t gwenesis_embedded_rom_size = (uint32_t)%d;\n" % size)

    out.write('const char gwenesis_embedded_rom_source[] = "%s";\n' % base.replace("\\", "\\\\").replace('"', '\\"'))

print("Written:", outpath, "(%d bytes, swap_pairs=%s)" % (size, swap_pairs))
print("Next: make -f Makefile.gwenesis")
PY

chmod a+r "$OUTFILE"
